### ISSUE TITLE
3.2.0-rc1 webinstaller deletes "DirectoryIndex disabled" from .htaccess hence breaks URL rewriting 

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-installer#103]
@dhensby

When installing 3.2.0-rc1 WITHOUT using _ss_environment.php, the webinstaller overwrites the following lines:

https://github.com/silverstripe/silverstripe-installer/blob/3.2/.htaccess#L36-L38

As a result, URL rewriting does not work properly. 

When using _ss_environment.php, these lines are not overwritten during an install and URLs rewriting works. 

See #58.

**Comment by tractorcow** [comment]
The issue is with https://github.com/silverstripe/silverstripe-framework/blob/3.2/dev/install/install.php5#L1542. It shouldn't be hard to fix. ;)

**Comment by SpiritLevel** [comment]
Thanks @tractorcow 

PR fixing #103 submitted.

**Comment by tractorcow** [comment]
I clicked that . :D

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4602
