### ISSUE TITLE
.htaccess should wrap SetEnv calls

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-installer#139]
The current .htaccess file (https://github.com/silverstripe/silverstripe-installer/blob/master/.htaccess) wraps one of the `SetEnv` calls in a `<ifmodule mod_env.c>` check, but doesn't wrap the one inside the mod_rewrite section.

We could either move the `SetEnv HTTP_MOD_REWRITE On` line up to sit under the other `SetEnv` call that is properly wrapped, or also wrap this line in the same `<IfModule mod_env.c>` check as the previous one.

**Comment by dcentrica** [comment]
The file mentioned by @madmatt is no longer valid for this issue. Run the following to discover all such files. The 2nd result is the one that should be patched:

```
find . -maxdepth 2 -type f -name .htaccess
```

**Comment by dcentrica** [comment]
Actually, I am blind. The one linked-to by @madmatt contains 2 lines (and still does in SS4) that should be wrapped.

```
#> less ./.htaccess
RewriteEngine On
RewriteRule ^(.*)$ public/$1
```

...these should be wrapped to. Can we re-open - it's a good one for the [Catalyst Academy](https://www.catalyst.net.nz/open-source-academy)

**Comment by kinglozzer** [comment]
Sure!

**Comment by maxime-rainville** [comment]
Can SS4 actually work without `mod_rewrite`? I had a quick got at it and didn't manage to do it.

**Comment by madmatt** [comment]
I'm not sure about SS4, but SS3 definitely can - all URLs just begin with /index.php?url=<normal mod_rewrite path>.
