### ISSUE TITLE
[4.0 alpha 2] Requirements Failure in install.php

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-installer#142]
I was trying to install a fresh copy SS4 alpha 2 and the requirements section of the install screen shows an unhelpful failure
![silverstripe_cms___framework_installation](https://cloud.githubusercontent.com/assets/1685217/18845189/a4808302-83ee-11e6-84e1-9347f604ec2e.png)

I'm using an ss_enviroement file, but this is still an issue even if I uncheck that option.

**Comment by baukezwaan** [comment]
Same here, I'm not using ss_environment. Just trying a plain installation

**Comment by thezenmonkey** [comment]
Reposted to silverstripe/framework since that really is where the code that is throwing this error lives
