### ISSUE TITLE
Apply "DirectoryIndex disabled" only to root directory

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-installer#144]
If you have a subfolder with a separate script (non-Silverstripe), you can add for example `RewriteRule ^shop - [L]` to make requests pass through to there, avoiding getting handled by SilverStripe. 

However, the current `DirectoryIndex disabled` rule in .htaccess prevents index pages in such subdirectories from working. 

Could that rule be changed so that it only applies to the root of the SilverStripe installation?

**Comment by dhensby** [comment]
If you drop a `.htaccess` in the directory in question you can make any change you like? You wouldn't even need to add the `RewriteRule ^shop - [L]` to the silverstripe `.htaccess`

**Comment by JorisDebonnet** [comment]
Hm, you're right, I'm not sure why I didn't get it to work before. I guess I didn't try the following, which was to add this in the subdirectory.
```
<IfModule mod_dir.c>
	DirectoryIndex index.php index.html
</IfModule>
```
