### ISSUE TITLE
[4.0.0-alpha3] Uncaught 'ReflectionException' after composer create-project

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-installer#145]
Hey all,

Just thought I'd try out the latest alpha, and installed it locally using:

```
composer create-project silverstripe/installer htdocs 4.0.0-alpha3
```

However, when I bring up the vhost in the browser, I receive a blank page, and PHP's error log reports:

```
[09-Nov-2016 14:50:23 Australia/Sydney] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class ErrorHandler does not exist' in W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Injector\InjectionCreator.php:13
Stack trace:
#0 W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Injector\InjectionCreator.php(13): ReflectionClass->__construct('ErrorHandler')
#1 W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Injector\Injector.php(558): SilverStripe\Core\Injector\InjectionCreator->create('ErrorHandler', Array)
#2 W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Injector\Injector.php(889): SilverStripe\Core\Injector\Injector->instantiate(Array, 'ErrorHandler')
#3 W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Core.php(103): SilverStripe\Core\Injector\Injector->get('ErrorHandler')
#4 W:\Sites\ss-alpha.dev\htdocs\framework\main.php(148): require_once('W:\\Sites\\ss-alp...')
#5 [internal function]: {closure}(Object(SilverStripe\Core\Startup\ErrorControlChain))
#6 W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Startup\ErrorControlChain.php(216): call_user_ in W:\Sites\ss-alpha.dev\htdocs\framework\src\Core\Injector\InjectionCreator.php on line 13
```

Perhaps there is a problem with the `composer.json` version constraints? I managed to get it working just fine with `dev-master`, so I suspect therein lies the answer.  😉

**Comment by tractorcow** [comment]
Hello, this could potentially be fixed by a patch merged post-alpha3 tag. Can you please update to this and check if that is the case?

https://github.com/silverstripe/silverstripe-framework/commit/f18ef75c3dbc843ad13e2769663eedb7d0f2593f

**Comment by colintucker** [comment]
Cheers Damo, will update and let you know shortly.  👍

**Comment by colintucker** [comment]
Confirmed, silverstripe/silverstripe-framework@f18ef75c3dbc843ad13e2769663eedb7d0f2593f fixes this issue, installer page is now coming up.

**Comment by tractorcow** [comment]
Thanks for confirming @colintucker, and apologies for the erroring alpha. Sorry you'll need to wait for alpha4 for it to be fixed. =(

**Comment by colintucker** [comment]
No worries @tractorcow - I can always `dev-master` 😉
