### ISSUE TITLE
Add installer warning about always_populate_raw_post_data=0

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-installer#147]
See https://github.com/silverstripe/silverstripe-graphql/issues/48#issuecomment-272049223 for context. This became an issue since starting to use POST bodies for GraphQL, but is a general problem which we can't solve directly for the user. For example, any API modules installed into an SS install might cause similar issues.

Add a warning (not an error) to the installer, tradeoff between being proactive about potential problems the dev might encounter, without forcing a php.ini change for virtually every PHP 5.6 install out there (and hence creating a barrier of entry/upgrade).

Document this new default in the 4.0.0 changelog as well. 

PR: https://github.com/silverstripe/silverstripe-framework/pull/6507

**Comment by sminnee** [comment]
Suggested message:

> always_populate_raw_post_data must be set to -1 in your php.ini in order to make use of request bodies other than form submissions. JSON/XML request bodies are an important part of building solid REST or GraphQL APIs so we recommend that you change this setting now. Changing this setting is needed to make use of the <u>GraphQL API</u> as we have documented it.

"GraphQL API" should link to the docs we have / are planning on how users can query their content via GraphQL. The start of that document should say:

> If you are running PHP 5.5 or 5.6, you should update your php.ini to set `always_populate_raw_post_data = -1`. If you don't do this, you can still use GraphQL via POST requests (this is what the CMS admin does in order to maximise compatibility) but this documentation doesn't cover that.
