### ISSUE TITLE
Block dev/test configuration files?

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-installer#154]
In addition to blocking common log files (#153) I would like to discuss also blocking all files in the webroot that do not need to be public (including php unit files, markdown files, .gitignore, build.xml) and so on.

Some developer, not knowing the ramification, might accidentally expose sensitive information through one of those files.
One might argue that it's the developers job to take care of blocking files that should not be public. But considering that this repository is primarily intended for people getting started with SilverStripe, I think more secure and restrictive defaults are appropriate.

**Comment by dhensby** [comment]
Seems sensible

**Comment by chillu** [comment]
Sure thing, PR welcome :) Closing as an enhancement ticket until then
