### ISSUE TITLE
Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::setPool()

### ISSUE THREAD

**Issue by mi32dogs** [silverstripe/silverstripe-installer#167]
This is the error i get when i try to install on a Google Instance  with Debian 8 and Mysql 5.6 "
Fatal error: Call to undefined method SilverStripe\Config\Collections\CachedConfigCollection::setPool() in /var/www/html/framework/src/Core/Config/CoreConfigFactory.php on line 51"

**Comment by dhensby** [comment]
duplicate of https://github.com/silverstripe/silverstripe-framework/issues/6737
