### ISSUE TITLE
Problem with missing package "php-intl"

### ISSUE THREAD

**Issue by minimalic** [silverstripe/silverstripe-installer#169]
Silverstripe 4.0 alpha 6 seems to need `php-intl` but there is no info in the installer. Installing `php-intl` let you install SilverStripe, but without `php-intl` it causes ugly PHP error :)

**Comment by robbieaverill** [comment]
This would be useful for those who don't install with composer initially (https://github.com/silverstripe/silverstripe-framework/issues/6627)

**Comment by sminnee** [comment]
I'm closing this as a duplicate of 6627 and 6765
