### ISSUE TITLE
Combined build: Add "--no-dev" build

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-installer#175]
https://github.com/silverstripe/silverstripe-framework/pull/6833 was kind of annoying and painful and I'd like to cover it with an automated test.

In my view it's more of an edge-case and can sit on our combined nightly build, rather than on the framework build executed with every PR.

I would probably describe this as "production smoke test", since it's designed to replicate a production environment, and it doesn't need to cover all unit tests.

I think this test pattern makes the most sense.

 * Install packages with --no-dev
 * Run dev/build
 * Validate that apache can deliver the homepage

The first 2 steps would have covered our failure case, but the 3rd is probably useful too. I expect that some of the test harness can be gleaned from the behat suite.

If you wanted, this could be structured as a behat test:

```
Given I execute "composer install --no-dev" on the command-line
Then I can execute "framework/sake dev/build" on the command-line
When I visit "/"
I see the text "Welcome to SilverStripe! This is the default homepage."
````

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-installer/pull/219

**Comment by tractorcow** [comment]
Done.
