### ISSUE TITLE
Add PHP7 builds to all 3.6 compatible core modules

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-installer#181]
Sorry, couldn't find a better place to add this on a public repo.
Now that we're supporting PHP7 in 3.6, we should consistently run builds against it. Framework already does (https://github.com/silverstripe/silverstripe-framework/blob/3/.travis.yml), but cms, reports, blog etc don't. 

Strictly speaking we only need to add PHP7 builds to core modules (since that's the declared support), but ideally we'll test all [commercially supported modules](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/) against it.

I could imagine PHP7 in 3.x will become popular over the next months, given the massive performance gains. And we should be proactive about this in our modules. I don't expect much work to reach compatibility, it's just a matter of editing a whole bunch of `travis.yml` files.

**Comment by robbieaverill** [comment]
I think that's the last of them

**Comment by chillu** [comment]
Legend!
