### ISSUE TITLE
.env.example not getting installed

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-installer#186]
When installing SS4 using the command

`composer create-project silverstripe/installer 4.0.0 4.0.0-alpha7`

the file `.env.example` isn't getting installed as the docs say it should.

**Comment by tractorcow** [comment]
Need to add `--prefer-source` to get non-dist files. Will update docs.

**Comment by tractorcow** [comment]
Updated at https://github.com/silverstripe/silverstripe-framework/issues/7097

**Comment by SpiritLevel** [comment]
Thanks @tractorcow :)

**Comment by dhensby** [comment]
Hmm, should `.env.example` not make the dists? It seems fairly important to me...
