### ISSUE TITLE
Complete release branch migration

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-installer#188]
* [x] Set composer branch for master alias to <next-major-release> on all repos (e.g. `5.x-dev` or `2.x-dev`)
 * [x] Alias “4.0.x-dev” to “4.x-dev” as well for people who have been installing that (it was our default branch alias on master) 
 * [x] Rename all release branches to only include the major digit (e.g. `4` instead of `4.0`)
 * [x] Ensure that the default branch is set to the release branch (`4` or `1`) for all repos
 * [x] Update open PRs that are suitable for for merge into 4.x/1.x to have 4/1 as their destination branch rather than master

---

* [x] Make sure you can run a clean install afterwards
  * [x] `composer create-project silverstripe/installer /path/to/project 4.0.0-beta1`
  * [x] `composer create-project silverstripe/installer /path/to/project 4.0.x-dev`
* [x] And Sam test this legacy alpha install with `composer update`

Do this for all the ~15 repos making up a core release.
- installer
- framework
- assets
- config
- versioned
- admin
- campaign-admin
- asset-admin
- siteconfig
- reports
- cms
- errorpage

excluded
- graphql

**Comment by sminnee** [comment]
We should probably alias "4.0.x-dev" to "4.x-dev" as well for people who have been installing that (it was our default branch alias on master)

To prevent this next time, I think that master's alias should be "5.x-dev" and not "5.0.x-dev"

**Comment by sminnee** [comment]
Recategorising as bug.

**Comment by sminnee** [comment]
Also you might want to add a task "Update open PRs that are suitable for for merge into 4.x/1.x to have `4`/`1` as their destination branch rather than `master`"

**Comment by flamerohr** [comment]
I've been running into issues with `composer create-project silverstripe/installer /path/to/project 4.0.x-dev`
which implies @sminnee's `composer update` wouldn't work, as it's producing the same error
```
The requested package silverstripe/campaign-admin 1.0.x-dev exists as silverstripe/campaign-admin[1.0.0-alpha6, 1.0.0-alpha7, 1.0.0-beta1, 1.x-dev, dev-master, 2.x-dev] but these are rejected by your constraint.
```

I had made this commit to see if branch-alias works as documented which said it needed to be on the branch.
https://github.com/silverstripe/silverstripe-assets/commit/70c4eb79779dfd63171e05107b303b953eb456ca

This has reached the limit to my understanding with how composer works, I'll need to do some research to figure out what is happening.
Currently, I'd advise not using `1.0.x-dev`/`4.0.x-dev` and stick with `1.x-dev`/`4.x-dev` until this is resolved.

**Comment by sminnee** [comment]
@flamerohr you've made changes to master and they should be merged to the 4 branch.

**Comment by flamerohr** [comment]
Everything looks good, a part from mid-commit issues last night :D

Got confirmation from Sam and Damian that `composer update` from previous alpha installs no longer cause issues
