### ISSUE TITLE
.editorconfig conflicts with 4-space composer.json expectation

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-installer#189]
Composer writes composer.json files using 4-spaces for tabs

.editorconfig declares 2 spaces for tabs, as package.json requires this.

We should update editorconfig with separate settings for package.json and composer.json, and decide what the default should be for other files.

 - [x] installer https://github.com/silverstripe/silverstripe-installer/pull/190
 - [x] framework
 - [x] asset-admin
 - [x] admin https://github.com/silverstripe/silverstripe-admin/pull/483
 - [x] cms
 - [x] versioned
 - [x] siteconfig
 - [x] reports
 - [x] assets
 - [x] campaign-admin
 - [x] behat-extension
- [x] errorpage
- [x] graphql https://github.com/silverstripe/silverstripe-graphql/pull/146
- [x] config https://github.com/silverstripe/silverstripe-config/pull/31
- [x] recipe-plugin https://github.com/silverstripe/recipe-plugin/commit/88cd7ed3a0c07a0b24b70ee43d855488d7f1ac7e

**Comment by robbieaverill** [comment]
PR for composer.json at #190. Personally I prefer four spaces for JSON but there isn't a specification for this - the JSON spec is for the structure rather than the presentation.

2 spaces seems to be more common these days in JSON files though.

**Comment by tractorcow** [comment]
Installer has been updated at https://github.com/silverstripe/silverstripe-installer/pull/190: We will need to fix all other modules.

**Comment by tractorcow** [comment]
I've updated the list above; Most modules are done but not yet all of them.

**Comment by robbieaverill** [comment]
Finito!
