### ISSUE TITLE
No cms or framework requirements in composer.json

### ISSUE THREAD

**Issue by nspyke** [silverstripe/silverstripe-installer#199]
This is regarding 4.0 beta 2.
When installing via composer, the composer.json require has
```
"require": {
    "php": ">=5.6.0",
    "silverstripe/recipe-plugin": ">=0.1@dev <1.0",
    "silverstripe/recipe-cms": "1.0.0-beta2",
    "silverstripe-themes/simple": "~3.2.0"
},
```

Expected;
```
"require": {
    "php": ">=5.5.0",
    "silverstripe/cms": "^4.0.0-beta2",
    "silverstripe/framework": "^4.0.0-beta2",
    "silverstripe-themes/simple": "~3.2.0"
}
```

Is this intended? Are we going to manage upgrades using the recipe modules instead?

**Comment by dhensby** [comment]
> Are we going to manage upgrades using the recipe modules instead?

yes.

I'm not fully on top of the recipe approach at the moment, but @tractorcow can probably provide more info if needed

**Comment by tractorcow** [comment]
By moving to recipes, we can much better control groups of stabilities without having to micro-manage them on a per-module basis.

If you want to inline any recipe, you can still get the level of control you're used to, should you need it.

Please read https://github.com/silverstripe/recipe-plugin for more information.
