### ISSUE TITLE
[4.0] Not checking for intl package

### ISSUE THREAD

**Issue by hailwood** [silverstripe/silverstripe-installer#205]
It's only after you've run through the installer and it's actually trying to install things that you get the error 

```
ERROR [Emergency]: Uncaught Exception: This backend requires the php-intl extension 
IN POST /install.php Line 31 in 
/var/www/vendor/silverstripe/framework/src/i18n/Data/Intl/IntlLocales.php
```

**Comment by dhensby** [comment]
framework's composer.json has the intl extension as a requirement so it shouldn't be possible to install the framework without an error being thrown.

Did composer not complain about missing extensions?

**Comment by hailwood** [comment]
Ah, you're right,

I realized I accidentally ran the create-project from outside of my docker container so it used my hosts extensions instead.

**Comment by mustaqit** [comment]
OK, what's the solution for this issue?
ERROR [Emergency]: Uncaught Exception: This backend requires the php-intl extension IN POST /silverstripe/install.php

Thanks in advance!

**Comment by mustaqit** [comment]
OK, I found solutions;
->just uncomment this line by removing semicolon in php.ini file 
;extension=php_intl.dll
then restart the server
->finally copy these icu* * * *.dll files from C:\xampp\php to C:\xampp\apache\bin

it fixed everything!

**Comment by gbaumeister** [comment]
One can download the installer from the official-website which includes the framework already. In this case one does not use composer at all and run into the problem as well.

**Comment by dhensby** [comment]
@gbaumeister that's correct but the zip exists for legacy reasons and we actually require composer for using SS.

If you use the zip to install the software manually we expect you'd read the server requirements and composer.json to make sure you have all the platform requirements.

There's not any way a PHP application can force an extension to be installed in PHP, it can only tell you you don't have it by means of an error

**Comment by gbaumeister** [comment]
That is correct. A initial check at Step 1 during the would be advisable though (where all other requirements are checked eg. SPL/curl/fileinfo).

**Current behavior**: Installer says `All Requirements Pass` when all other requirements but php-intl are met, and the installation fails only later (leaving you with a broken installation).

**Expected behavior**: Installation tells you at Step 1 that `php-intl` extension is required, and hinders the user to continue with the installation.

Would be willing to provide a PR if accepted...

**Comment by dhensby** [comment]
> Would be willing to provide a PR if accepted...

It would be ;)
