### ISSUE TITLE
Can't access resources (on Vagrant machine) => CMS doesn't work during local development

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-installer#206]
This issue may be specific to running a web server on a virtual machine with synced source code to your host machine. But that may be a pretty common way to develop locally. It also makes me wonder how those symbolic links will actually fare after going through a git repository.

After having installed SilverStripe 4.0.0rc3 (from my Windows machine), the CMS (hosted by the Vagrant machine on Ubuntu) has no styling or javascript because the web server refuses to serve the files that go through one of those symbolic links in the `resources` folder. I ssh'd into the server to try and find the spinner icon: I went into `resources/silverstripe/admin/client/` and this is what it shows me: 
```
vagrant@homestead:~/code/ozg/resources/silverstripe/admin/client$ ls -la
ls: cannot read symbolic link 'dist': Protocol error
ls: cannot read symbolic link 'lang': Protocol error
total 3
drwxrwxrwx 1 vagrant vagrant    0 Nov  4 18:55 .
drwxrwxrwx 1 vagrant vagrant    0 Nov  4 18:55 ..
lrwxrwxrwx 1 vagrant vagrant    0 Nov  4 13:48 dist
lrwxrwxrwx 1 vagrant vagrant    0 Nov  4 13:48 lang
vagrant@homestead:~/code/ozg/resources/silverstripe/admin/client$ cd dist
-bash: cd: dist: Protocol error
```

I guess you could argue this is a Vagrant bug, but maybe there's a way to circumvent it? Maybe the symbolic links can be created upon first run (by the web server user) instead of by the composer recipe (or whatever it is creating them)?

# PR

 - [ ] https://github.com/silverstripe/vendor-plugin/pull/11

**Comment by JorisDebonnet** [comment]
As expected, I could fix this issue by removing my project and just restarting with a `composer create-project silverstripe/installer . 4.0.x-dev` run from inside the web server (after having ssh'ed in). 

But I think it would still be useful if those symbolic-link-creations happened during one of the first HTTP request handlers, then people developing with local VMs can just continue as usual :)

**Comment by tractorcow** [comment]
For the time being you can install https://github.com/silverstripe/vendor-plugin-helper and run `vendor-plugin-helper copy /path/to/www` to force your site to copy resources rather than symlink / junction.

An example of this issue in the wild: https://stackoverflow.com/questions/37853544/cannot-read-symbolic-link-error-when-using-junction-folder

**Comment by tractorcow** [comment]
> But I think it would still be useful if those symbolic-link-creations happened during one of the first HTTP request handlers instead:

Will this actually fix the issue? Can you resolve this manually, and show that this would fix your issue @JorisDebonnet ?

**Comment by JorisDebonnet** [comment]
> Will this actually fix the issue? Can you resolve this manually, and show that this would fix your issue @JorisDebonnet ?

Well, I already verified that it works if I 'composer-install' the project from within the VM (see the first part of my previous reply). It will in fact be even more likely to work if the symlinks are created during the handling of a web request, because then you know they are created by same system user that will later be handling the requests for resources found through those symlinks. It's all about the permissions of those symlinks!

The reason it didn't work before for me is because the symlink on my system was created in Windows (via Git Bash), and apparently the permissions for it didn't sync correctly to Ubuntu on the VM. Perhaps they were created by 'root', and then the web-user can't use it. Symlinks are weird things permission-wise, I guess because there can be confusion about whether you're referencing the symlink itself or the directory it's pointing to.

So yeah, I am convinced that creating the symlinks during an installation request will be the most sure way to ensure they will work for future requests. [php's symlink function](http://php.net/manual/en/function.symlink.php) is available on Windows too, since php 5.3 (assuming the version of Windows supports symlinks).

**Comment by tractorcow** [comment]
@JorisDebonnet at the moment windows installs attempt to use junctions, not symlinks. Would it be better for us to explicitly split out the junction option into a separate `SS_VENDOR_METHOD` option, so you could use either `SS_VENDOR_METHOD=junction` or `SS_VENDOR_METHOD=symlink` explicitly? At the moment we only support `symlink`, but internally use junctions if on the windows platform.

**Comment by JorisDebonnet** [comment]
> Would it be better for us to explicitly split out the junction option into a separate `SS_VENDOR_METHOD` option, so you could use either `SS_VENDOR_METHOD=junction` or `SS_VENDOR_METHOD=symlink` explicitly?

@tractorcow Does that mean this value would have to be manually set in the .env file? That would mean people would still run into the issue and have to look for a solution, while of course it would be better if it 'just worked' regardless of setup. Unless I misunderstood you :) 

Actually, I see that the resources folder is .gitignored by default. How can one regenerate it after cloning an existing project? I tried `/dev/build` and `?flush=all`, but these don't do anything. 
Could those junctions/symlinks be created during the building of the cache, and so also during a flush? That may solve two issues at once (this very issue, and regenerating after cloning). It does require write access on the root folder during flushes, or at least to the resources folder. (Could consider moving it into the assets folder for that reason, since that one already requires permissions)

Or is there a reason the resources folder is required _before_ the first cache build or web request?

**Comment by tractorcow** [comment]
> @tractorcow Does that mean this value would have to be manually set in the .env file?

You could set it on your machine's global ENVs, so that it persisted for future projects also.

> Actually, I see that the resources folder is .gitignored by default. How can one regenerate it after cloning an existing project?

You would need to use the https://github.com/silverstripe/vendor-plugin-helper tool for now.

We should probably add a composer command that would regenerate these links, however, similar to `composer recipe-update`

**Comment by tractorcow** [comment]
Raised this issue over at https://github.com/silverstripe/vendor-plugin/issues/9

The issue of making a vagrant container fixing links created in a parent windows host is a bit harder to solve. It's likely that users in this situation will need to apply some kind of manual fix; We just need to ensure we test and document this fix well.

**Comment by dhensby** [comment]
I'm confused with this issue - I run my sites through vagrant and don't experience any problems with symlinks/copy not working...

Are you running composer from inside the VM or outside?

**Comment by tractorcow** [comment]
Probably because @JorisDebonnet is using windows as their host machine; Are you using OSX as I am @dhensby ?

Installation via composer on windows uses junctions instead of symlinks, which doesn't synchronise well when shared with a virtualized container.

**Comment by dhensby** [comment]
> Probably because @JorisDebonnet is using windows as their host machine; Are you using OSX as I am @dhensby ?

Nope I'm windows5lyf

**Comment by JorisDebonnet** [comment]
Well, I did run composer from Windows - I do all installation and development there. I usually don't have to go into the vagrant machine, but I did have to this time, to remake those symlinks. 

I do know that some versions of Windows supports symlinks, but I'm not sure SilverStripe takes that into account. I'm on Windows 10 and had the issue. Perhaps SilverStripe can try creating symlinks on Windows too, and only upon failure create junctions instead; that would make it a bit more consistent?

**Comment by tractorcow** [comment]
> I do know that some versions of Windows supports symlinks, but I'm not sure SilverStripe takes that into account. I'm on Windows 10 and had the issue. Perhaps SilverStripe can try creating symlinks on Windows too, and only upon failure create junctions instead; that would make it a bit more consistent?


It follows core composer behaviour; All windows versions use junctions, regardless of whether it supports symlinks or not.

**Comment by tractorcow** [comment]
@JorisDebonnet I've made a go at improving the vendor-plugin module, and have added an extra composer command you can use for modifying / fixing the resources folder.

https://github.com/silverstripe/vendor-plugin/pull/11

On your windows machine you should be able to just do `composer vendor-expose copy` and it'll fix your environment. :)
