### ISSUE TITLE
Installer uses a really old logo with copyright symbol, needs updating 

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-installer#221]
I didn't see any logo file directly in the installer itself so it must be referencing a file in another repo?

**Comment by robbieaverill** [comment]
The assets are coming from framework: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Dev/Install/client/images/logo.gif

**Comment by clarkepaul** [comment]
I'm guessing this can be closed now the installer is no longer?
