### ISSUE TITLE
Suggestion: disallow HTTP access to .git folder

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-installer#226]
By default, any website deployed using git has its `.git` folder published. But not everyone wants their repository to be public. Some might even store passwords somewhere in there and unknowingly publish it this way. This can be solved by disallowing access to the `.git` folder by default.

I assume this is only relevant for 3.x and 4.0 however, thanks to 4.1's `public` folder.

E.g. in `.htaccess`:
```
# Disallow access to git repository
RedirectMatch 404 ^/.git/
```
Although I suppose it could also just use the same structure as how `composer.json` etc are disallowed. 

I don't know how to do it in the `web.config` thing.

**Comment by robbieaverill** [comment]
Maybe any path that begins with `.` should be blocked?

**Comment by JorisDebonnet** [comment]
> Maybe any path that begins with . should be blocked?
Makes sense, yeah; I see that e.g. my `.gitignore` is still accessible which shouldn't be the case either :)

**Comment by dhensby** [comment]
This should really be configured at a server level :/ I'm sure this has been discussed before..

**Comment by JorisDebonnet** [comment]
Let us continue the discussion on #227.

**Comment by chillu** [comment]
See https://github.com/silverstripe/silverstripe-installer/pull/227
