### ISSUE TITLE
Placeholder: revert tag backmerges into minor branches

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-installer#235]
The tags that were merged back into branches need to be undone, as they contain strict stable constraints which are reserved _only_ for tags. The commit that exists in these tags should never be merged back into the branches: https://github.com/silverstripe/recipe-cms/blob/4.2/composer.json https://github.com/silverstripe/silverstripe-installer/blob/4.2/composer.json#L8

This prevents any modules from using 4.2.x-dev in Travis builds.

**Comment by dhensby** [comment]
gah - sorry

**Comment by dhensby** [comment]
Fixed with 986a2f9

**Comment by dhensby** [comment]
oh no! :(

**Comment by dhensby** [comment]
fixed recipe-cms: https://github.com/silverstripe/recipe-cms/commit/48138b11f61c3f7608e3bd61d36e049ed3302892
