### ISSUE TITLE
4.3.1 tarballs include git history

### ISSUE THREAD

**Issue by ntd** [silverstripe/silverstripe-installer#251]
No idea if this is the proper project: please, feel free to move it to the appropriate one or tell me where I must file this issue against and I'll move it by myself.

Follow up of this [forum thread](https://forum.silverstripe.org/t/unused-files/1682): SilverStripe 4.3.1 [released packages](https://www.silverstripe.org/download) have a size of 295 Mb (.zip) and 289 Mb (.tar.gz) while 4.3.0 were 14 and 11 Mb. I guess 4.3.1 is including all the git history.

I think this was just an oversight: I cannot believe it was a conscious decision.

**Comment by dnsl48** [comment]
Yes, looks like a mistake, thank you for reporting @ntd

**Comment by DorsetDigital** [comment]
I'm sure it's known, but the 4.4.1 release has the same issue. The downloads on the site are in excess of 300Mb

**Comment by dnsl48** [comment]
related issue: https://github.com/silverstripe/cow/issues/136

**Comment by chillu** [comment]
We stopped doing archive releases, so this is a non-issue now
