### ISSUE TITLE
Public-Redirect is Missing for IIS/ASP

### ISSUE THREAD

**Issue by manuth** [silverstripe/silverstripe-installer#262]
All requests must be redirected to the `public/`-directory.
The root-directory of this repo has a `.htaccess`-file for redirecting all Apache-requests to the `public/` folder but no `web.config`-file to do the same for IIS/ASP.NET-requests.

**Comment by Cheddam** [comment]
Hi @manuth, thanks for raising this! Would you be interested in raising a pull request to add the required `web.config` file?

**Comment by manuth** [comment]
You're welcome
And of course, just give me some seconds ^^

**Comment by manuth** [comment]
Sorry for the late response
Building a Windows docker container is harder than I expected.

According to [Microsoft's official docs](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#rules-inheritance):
> Evaluate a rule set that includes distributed rules from parent configuration levels as well as rules from the current configuration level.

Which means that rewriting a URL to `public/*` won't cause the `public/webconfig`'s rewrite-rules to be processed as only the current configuration level (which is `.`) is considered.

Therefore I had to merge `web.config` and `public/web.config`.
If working with `public/` is the only correct approach to work with SilverStripe you might want to delete the now obsolete rewrite rule from the [public web.config-file](
https://github.com/silverstripe/recipe-core/blob/3561466e5ea479ee5602451d9fe2240a952ed56a/public/web.config#L18-L28) as this rule is merged into the `silverstripe-installer`'s `web.config` now.
