### ISSUE TITLE
CMS 4.5.1 release

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-installer#274]
Taken from draft PR (#264)

# Security release checklist

## Planning

- [x] Internal comms have been made with intended release date
  - [x] #cwp-and-oss-releases
  - [x] Marketing
- [x] All issues in milestone are closed or reassigned

## Preparation

*Start ~1 week before intended release date*

- [x] All security fixes requiring pre-disclosure (CVSS >= 7.0) have been disclosed in the [security-preannounce](https://groups.google.com/a/silverstripe.com/forum/#!forum/security-preannounce) group.
- [x] Security pre-annoucements are general enough to convey importance, but not specific enough to put affected sites at risk.
- [x] Draft disclosures of each fix have been created on the [security releases page](https://www.silverstripe.org/download/security-releases/).
- [x] Security pages are populated with the information from the [Github project board](https://github.com/silverstripe-security/security-issues/projects/1).
- [x] Each disclosure has versions affected, description, and, if applicable, a CVE identifier and [CVSS score](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator)
- [x] Changelog links to [security releases](https://www.silverstripe.org/download/security-releases/) detail page
- [x] All security fixes in the release are in the "Awaiting release" column on the [project board](https://github.com/silverstripe-security/security-issues/projects/1)
- [x] Security repos are up to date with their public counterparts (double checked on release day, but keeping them up to date will minimise surprises)

## Execution

- [x] Push all affected public repositories to their respective private security repositories (e.g. `git pull origin 4 && git push security 4`).
- [x] Review each pull request in the security repositories. Check that after syncing, there are:
  - [x] No new merge conflicts
  - [x] Tests are passing
  - [x] No new comments that require a response
- [x] Merge each pull request once the above criteria are met
- [x] Wait for builds to go green
- [x] When green, push security upstreams to their respective public repositories
- [x] **I understand that the security issues have now been publicly disclosed**

- [x] Merge up minor release branches and push directly to origin
- [x] `$ cow release:create [version] silverstripe/installer`
- [x] `$ cow release:plan [version] silverstripe/installer`
- [x] Use the [cow-compare](https://gist.github.com/unclecheese/0683140b8d1300638131ba9e9b20ee78) command to determine what modules need new tags. If the compare is empty or includes only non-functional changes, use current tag. See [open PR](https://github.com/silverstripe/cow/pull/144) to merge this script into core cow functionality.
- [ ] `$ cow release:branch [version] silverstripe/installer`
- [x] `$ cow release:translate [version] silverstripe/installer`
- [x] `$ cow release:changelog [version] silverstripe/installer`
  - [x] Review changelog:
    - [x] Preamble is in publishable state:
      - [x] Major changes announced
      - [x] Upgrading notes included (if applicable)
      - [x] All security fixes (if applicable) are included
      - [x] No typos
    - [x] No duplicates
    - [x] No merge commits
- [x] Smoke test release by running ~release webroot in localhost or VM~ a selection of scenarios in HipTest
- [ ] `cow release:tag [version] silverstripe/installer`

## Publication

- [x] All security issues are in the "done" column
- [x] Minor release branches merged up
- [x] New tag is on [releases](https://github.com/silverstripe/silverstripe-installer/releases) page
- [x] Current milestone closed, new milestone created
- [x] demo.silverstripe.org updated
  - [x] Update composer.json to new minor release
  - [x] Deploy
- [x] docs.silverstripe.org updated:
  - [x] New changelog showing
  - [ ] Links to changelogs in announcements work
- [x] Announce in the ["Releases" forum](https://forum.silverstripe.org/c/releases)
- [x] #ss4 Slack channel topic shows newest release with link to changelog
- [x] Security release pages published
- [x] Response to issue reporter with reference to the release on the same discussion thread (cc security@silverstripe.org) sent
- [x] [CVE publication request](https://cveform.mitre.org/) submitted with link to disclosure on silverstripe.org
- [ ] PR to [FriendsOfPHP/security-advisories](https://github.com/FriendsOfPHP/security-advisories) raised with CVE details
- [ ] Comms to OS teams and marketing

**Comment by robbieaverill** [comment]
Note that framework 4.5.1 has just been tagged, in case there is any confusion when compiling this release (you'll need to release 4.5.2 if there are any security fixes for framework)

**Comment by dnsl48** [comment]
A note for the person performing the following security release:
 - Update OpenSource [documentation](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/05_Contributing/05_Making_A_SilverStripe_Core_Release.md#first-time-setup), describing how exactly we use Satis
 - Potentially add a patch to Cow docker setup/documentation to link Satis from within the container if necessary (or maybe install Satis within the container if necessary).
