### ISSUE TITLE
new install results in duplicate assets yml config

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-installer#277]
after setting up a new project (`composer create-project project-name 4.5.2`) I have noticed that in `app/_config` there is very similar (1 line difference) config for the assets module for SS4.4+, looking into this deeper this seems to be caused by https://github.com/silverstripe/recipe-core/blob/4/app/_config/mysite.yml and https://github.com/silverstripe/silverstripe-installer/blob/4/app/_config/assets.yml

Unsure which version should be used and maybe not necessary in `silverstripe-installer` now it's included in `recipe-core`?

# Pull requests
* [ ] https://github.com/silverstripe/recipe-core/pull/59

**Comment by Cheddam** [comment]
Nice catch @christopherdarling - definitely seems like only one of these should exist!

@maxime-rainville any chance you could shed some light on this?

**Comment by maxime-rainville** [comment]
WOW ... not sure what I was thinking there. 

This should fix it https://github.com/silverstripe/recipe-core/pull/59

**Comment by maxime-rainville** [comment]
Fixed by https://github.com/silverstripe/recipe-core/pull/59
