### ISSUE TITLE
Failing tests on 4 branch

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-installer#282]
See: https://travis-ci.org/github/silverstripe/silverstripe-installer/builds/698547966

![image](https://user-images.githubusercontent.com/15868440/84714754-aed60800-afc2-11ea-984d-858408d19642.png)

**PRs**
- [x] https://github.com/silverstripe/silverstripe-installer/pull/283

**Comment by emteknetnz** [comment]
Fixed now
