### ISSUE TITLE
create-project includes an unnecessary .cow directory

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-installer#287]
I don't understand the purpose of the `.cow` directory - I know what `cow` is for but I don't know why there's a file in there that's added to every project that starts with `composer create-project silverstripe/installer`. If the file is required, could it be ignored by composer maybe somehow?

**Comment by robbieaverill** [comment]
Yes, we can add it to .gitatttibutes so it's ignored in tagged distributables. It's there for us to do releases with, but that always happens from a dev version which is not affected by git attributes rules.

**Comment by maxime-rainville** [comment]
Got a PR at https://github.com/silverstripe/silverstripe-installer/pull/288

**Comment by madmatt** [comment]
<3 Thanks team!
