### ISSUE TITLE
Composer update running out of memory on travis

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-installer#305]
The composer v1 builds are running out memory.  Composer v2 is fine.

https://travis-ci.com/github/silverstripe/silverstripe-installer

I think it's still worth keeping the composer v1 around for now since lots of people will still be using that

### PRs
- [x] https://github.com/silverstripe/silverstripe-travis-shared/pull/18

**Comment by maxime-rainville** [comment]
PR has been merged. It's worth pointing out the stated future plan for composer 1. https://blog.packagist.com/deprecating-composer-1-support/
