### ISSUE TITLE
Does it support PHP 8.0.12?

### ISSUE THREAD

**Issue by ramseyjiang** [silverstripe/silverstripe-installer#311]
When I used composer try to install ss in my local env, it has issues below:

$composer create-project silverstripe/installer ss_example

Creating a "silverstripe/installer" project at "./ss_example"
Installing silverstripe/installer (4.9.0)
  - Installing silverstripe/installer (4.9.0): Extracting archive
Created project in /Users/jiangdawei/Desktop/PHPApp/ss_example
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sminnee/phpunit[5.7.28, ..., 5.7.x-dev] require phpunit/php-code-coverage ^4.0.4 -> satisfiable by phpunit/php-code-coverage[4.0.4, ..., 4.0.8].
    - phpunit/php-code-coverage[4.0.4, ..., 4.0.8] require php ^5.6 || ^7.0 -> your php version (8.0.12) does not satisfy that requirement.
    - Root composer.json requires sminnee/phpunit ^5.7 -> satisfiable by sminnee/phpunit[5.7.28, 5.7.29, 5.7.x-dev].

**Comment by ramseyjiang** [comment]
So I don't know whether this version supports PHP 8.0.12 or not?

**Comment by maxime-rainville** [comment]
Silverstripe CMS Recipe 4.10 will have full support for PHP8 and PHPUnit9. You can learn more on this issue: https://github.com/silverstripe/silverstripe-framework/issues/10019

You can install Silverstripe CMS Recipe 4.9 by removing the dev dependencies that are not installable on PHP8 or by using the `--ignore-platform-reqs` flag with your composer command. But you won't be able to run unit tests.
