### ISSUE TITLE
CMS5 Upgrade all other installer dependencies

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-installer#335]
Upgrade all dependencies in the base installer to use a recent a supported version.

## Acceptance criteria
- [ ] All PHP dependencies in tho core modules have been reviewed and updated if need be

Follow up from these cards:
- https://github.com/silverstripe/silverstripe-framework/issues/10487
- https://github.com/silverstripe/silverstripe-assets/issues/497

### PR''s

- https://github.com/silverstripe/silverstripe-config/pull/71
- https://github.com/silverstripe/silverstripe-frameworktest/pull/128
- https://github.com/silverstripe/silverstripe-graphql/pull/502
- https://github.com/silverstripe/silverstripe-mimevalidator/pull/59
- https://github.com/silverstripe/MinkFacebookWebDriver/pull/23
- https://github.com/silverstripe/recipe-plugin/pull/28
- https://github.com/silverstripe/recipe-testing/pull/13
- https://github.com/silverstripe/silverstripe-reports/pull/155
- https://github.com/silverstripe/silverstripe-serve/pull/36
- https://github.com/silverstripe/silverstripe-siteconfig/pull/129
- https://github.com/silverstripe/silverstripe-testsession/pull/82
- https://github.com/silverstripe/vendor-plugin/pull/61
- https://github.com/silverstripe/silverstripe-versioned/pull/376
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/261

**Comment by sabina-talipova** [comment]
### List of module upgrades:
- [x] **silverstripe-config:**
  - [x] "psr/simple-cache": "^1.0.1" => "^3.0.0"
  - [x] "squizlabs/php_codesniffer": "^3.5" => "^3.7"
- [x] **silverstripe/frameworktest:**
  - [x] "guzzlehttp/guzzle": "^7.4.5" => "^7.5"
  - [ ] **"fzaninotto/faker": "^1.9.2"** => `This package is abandoned and no longer maintained. No replacement package was suggested.`
- [x] **silverstripe/graphql:**
  - [x] "webonyx/graphql-php": "^14.11.6" => "^14.11.8"
  - [x] "guzzlehttp/guzzle": "^7.4.5" => "^7.5.0"
  - [x] "guzzlehttp/psr7": "^2.4.0" => "^2.4.1"
- [x] **silverstripe/mimevalidator:**
  - [x] "nikic/php-parser": "^4.14.0" => "4.15.0"
- [x] **silverstripe/mink-facebook-web-driver:**
  - [x] "php-webdriver/webdriver": "^1.12.1" => "^1.13.1"
- [x] **silverstripe/recipe-plugin:**
  - [x] "squizlabs/php_codesniffer": "^3.5" => "^3.7"
- [x] **silverstripe/recipe-testing:**
  - [x] "squizlabs/php_codesniffer": "^3" => "^3.7"
- [x] **silverstripe/reports:**
  - [x] "squizlabs/php_codesniffer": "^3.0" => "^3.7"
- [x] **silverstripe/serve:**
  - [x] "squizlabs/php_codesniffer": "^3" => "^3.7"
  - [x] "symfony/process": "^4.0" => "6.1.3"
- [x] **silverstripe/siteconfig:**
  - [x] "squizlabs/php_codesniffer": "^3" => "^3.7"
- [x] **silverstripe/testsession:**
  - [ ] "squizlabs/php_codesniffer": "^3.5"  => "^3.7" 
- [x] **silverstripe/vendor-plugin:**
  - [x] "squizlabs/php_codesniffer": "^3" =>  "^3.7"
- [x] **silverstripe/versioned:**
  - [x] "squizlabs/php_codesniffer": "^3" => "^3.7"
- [x] **silverstripe/versioned-admin:**
  - [x] "squizlabs/php_codesniffer": "^3" => "^3.7"

**Comment by GuySartorelli** [comment]
All PRs merged.
