### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-installer#337]
installer + framework
https://github.com/silverstripe/silverstripe-installer/actions/runs/3370916046/jobs/5592440767

> Failed asserting that exception message 'Config SilverStripe\Control\HTTP.disable_http_cache is deprecated. Use HTTPCacheControlMiddleware.defaultState/.defaultForcingLevel instead.' contains 'SilverStripe\Dev\Tests\DeprecationTest->testNotice is deprecated. My message. Called from PHPUnit\Framework\TestCase->runTest.'.

PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10563

**Comment by GuySartorelli** [comment]
PR merged and test green
