### ISSUE TITLE
RedirectMatch blocking some Themes files

### ISSUE THREAD

**Issue by colymba** [silverstripe/silverstripe-installer#34]
The addition of the RedirectMatch rules by 23523175f38a4aa5a21a6f98ef44918e2b6774f6 mainly `RedirectMatch 403 /vendor(/|$)` blocks any files in a vendor folder. This cause issues for example in themes where JS files for example could be served from a vendor subfolder.

An example is for a Themes using the HTML5 Boilerplate where JQuery and Modernizer are saved in a vendor folder.

Maybe a better solution is to use something like `^/?vendor(/|$)` filtering only request starting with vendor?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-installer/commit/aa07a0edd87f0bf88ec259c500d5355046686d9f
