### ISSUE TITLE
CMS 5: Ensure correct constraints for vendor-plugin and recipe-plugin before release

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-installer#341]
In https://github.com/silverstripe/silverstripe-admin/issues/1318 we changed the constraint for `silverstripe/recipe-plugin` and added `silverstripe/vendor-plugin` as an explicit dependency of installer both with constraint `2.x-dev`. This was to resolve a problem where the alpha release was being checked out in CI when we needed the dev branch.

When we do a release, we need to make sure the release includes the correct stability constraints for these. There are two ways to handle that:
1. Make sure these plugins are handled by cow. Cow already knows how to deal with these constraints, so it just needs to know it is meant to handle the constraints for _these_ dependencies as well.
1. Manually revert these constraints to `^2` before we do a release. This solution is simpler but it runs the risk of the same thing happening to us again at some future point in time.

Note: also need to do the same for recipe-kitchen-sink (see https://github.com/silverstripe/recipe-kitchen-sink/pull/26)

### PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/30
- https://github.com/silverstripe/silverstripe-installer/pull/349

**Comment by emteknetnz** [comment]
Chatted offline - we'll manually release 2.0.0 for silverstripe/vendor-plugin and silverstripe/recipe-plugin and update constraints to ^2

**Comment by GuySartorelli** [comment]
All done
