### ISSUE TITLE
Unexpected new dev dependencies in recent installs

### ISSUE THREAD

**Issue by AmadeoMB** [silverstripe/silverstripe-installer#343]
## Affected Version

Silverstripe 4.12

## Description

Hi there,
I just installed a silverstripe through a composer and added a couple of data objects. And as soon as I dev/build them, I got some unknown data objects, it got some records too btw. Is this supposed to happen? If it's yes, How can I hide them?

Here is the unknow data objects:
- Test React FormBuilder
- Elemental Behat Test Admin
- GridField Test Navigation
- Registry
- Test ModelAdmin

## Steps to Reproduce

- I ran `composer create-project silverstripe/installer .`
- Making a couple of data objects (This step might be doesn't mean anything but this is how I got them)
- Running dev/build
- Go to CMS Admin and there you go

## ACs
- [x] silverstripe/installer require-dev is reverted to what was in 4.11
- [x] dependencies that were in require-dev are moved to ci.yml
- [x] 4.12.1 is released which includes the correct `~` requirements rather than `.x-dev` requirements

## PRs
- https://github.com/silverstripe/silverstripe-installer/pull/344
- https://github.com/silverstripe/silverstripe-installer/pull/345
- https://github.com/silverstripe/silverstripe-installer/pull/346

**Comment by punk2000** [comment]
Same issue here, the admin is flooded with test data. 
`composer remove silverstripe/frameworktest` removes the mess in the admin. 
(Best case you run this before dev/build)

**Comment by emteknetnz** [comment]
Apologies about this, this was unintentional, we'll fix this fairly shortly so that it's removed from silverstripe/installer 4.12.1

**Comment by GuySartorelli** [comment]
@AmadeoMB @punk2000 For new projects you have already created, you can remove the following from `require-dev` in your `composer.json` file:
- silverstripe/recipe-testing
- silverstripe/frameworktest

You might want to start a new database from scratch, or if you need to retain your existing database, you'll want to remove the test records that were created automatically by `silverstripe/frameworktest`.

**Comment by emteknetnz** [comment]
@AmadeoMB @punk2000 We've released [4.12.1](https://github.com/silverstripe/silverstripe-installer/releases/tag/4.12.1) of silverstripe/installer with the test data removed

`composer create-project silverstripe/installer` now works as intended
