### ISSUE TITLE
index.php does not redirect properly when positioned in the server's webroot

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-installer#38]
From http://open.silverstripe.org/ticket/3953

Needs to be tested with latest implementation. If useful use.

=== modified file 'index.php'
--- index.php	2009-04-17 15:36:30 +0000
+++ index.php	2009-04-29 20:14:35 +0000
@@ -54,7 +54,10 @@
  * Very quickly pass through references to files
  */
 if($url && file_exists($fileName)) {
-	$fileURL = dirname($_SERVER['SCRIPT_NAME']) . '/' . $url;
+	$baseURL = dirname($_SERVER['SCRIPT_NAME']); 
+	if($baseURL == "\\" || $baseURL == "/") $baseURL = ""; 
+	$fileURL =  "$baseURL/$url"; 
 	header($_SERVER['SERVER_PROTOCOL'] . ' 301 Moved Permanently');
 	header("Location: $fileURL");
 	die();

**Comment by dhensby** [comment]
This was fixed some time ago
