### ISSUE TITLE
Assets are not accessible due to 500 error

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-installer#67]
Apache 2.4.10
PHP 5.5.15

composer create-project silverstripe/installer ssbase

Trying to access assets/Uploads/SilverStripeLogo.png results in a 500 - as would every other item in assets.

[Sat Aug 16 22:14:37.822485 2014] [core:alert] [pid 1848] [client ::1:39063] /home/nightjar/public_html/ssbase/assets/.htaccess: php_flag not allowed here, referer: http://localhost/~nightjar/ssbase/admin/assets/show/1

The offending line is one of the directives attempting to disable the php engine. Commenting allows the asset to load.

Making an issue rather than a PR because not sure that this isn't just a configuration issue (I'm using my distro's defaults, but that doesn't mean all that much).

**Comment by dhensby** [comment]
This looks like it was fixed some while ago as the php_flag is wrapped in an `<IfModule>` block.

@NightJar are you still experiencing this?

**Comment by NightJar** [comment]
Unsure, the VM has been updated since then. I'll give it a go and see though. I don't often use/need cms, so tend to just require framework directly - so this was a try, fail, report, care less sort of arrangement.

**Comment by dhensby** [comment]
Ok, no worries. I'd have expected more complaints about this if it was an ongoing issue... If you don't mind checking and closing this off (if it's not a problem) that'd be great :)

**Comment by NightJar** [comment]
Alright, after some lengthy investigation (and self tutoring on apache configs), it is just a configuration issue as I originally thoguht it might have been.

I am using the userdirs apache module (as moderately evident by my original post), so it wasn't a virtual host issue... as such.
But the default configuration as of Apache 2.4 is now of course `AllowOverride none`
The default userdirs config however sets:
```
<Directory "/home/*/public_html">
    AllowOverride FileInfo AuthConfig Limit Indexes
    Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
    Require method GET POST OPTIONS
</Directory>
```
Simply adding Options to the end of the AllowOverride list (then reloading the config) has sorted the issue.

The failure came despite ifmodule because of course the module exists and was loaded, but the flag to configure it was not allowed in .htaccess, causing a fatal error.

Thanks for reminding me on this @dhensby - I was able to look into it now that I had more free time.

**Comment by dhensby** [comment]
Awesome, glad it's sorted... perhaps you could add this to the docs? :)

**Comment by NightJar** [comment]
Point me in the right direction and I'll consider it ;)

**Comment by dhensby** [comment]
https://github.com/silverstripe/silverstripe-framework/edit/3.1/docs/en/00_Getting_Started/01_Installation/05_Common_Problems.md looks like the best bet!
