### ISSUE TITLE
[proposal] deny access to README.md via htaccess

### ISSUE THREAD

**Issue by ivoba** [silverstripe/silverstripe-installer#70]
Since Silverstripe installs fully in the web root all files are theoretically accessable.
Wouldnt it be good to deny access to the README.md via htaccess by default then.

You might want to add specific project documentation to the README.md to describe some hacks or specialities to the colleagues.  
This renders nice in your private repo but the information is sometimes/often not suited for public, so you would have to deny access yourself, which can be forgotten.
To have this protection by default would be nice, wouldnt it?

Btw, even this: http://www.silverstripe.org/README.md which is currently accessable, i rather find sketchy ;)

**Comment by ss23** [comment]
I vote no. Instead we should devote time to refactoring SilverStripe such that the webroot only contains files that need to be accessible. Playing whack-a-mole with sensitive files is a losing battle.

**Comment by dhensby** [comment]
I agree. It's not great that everything is installed into the webroot with SS, but that doesn't mean we should be completely defensive about it.

If you have project repos where you're doing all your code (including sensitive readmes) in the webroot, then it's that internal process that needs overhauling and/or you need to add custom rules to your .htaccess
