### ISSUE TITLE
web installation ss 3.1.8

### ISSUE THREAD

**Issue by JStika** [silverstripe/silverstripe-installer#75]
It's shame! It's shame! It's shame! 

I think, it must be reopened for ss 3.1.8. 
It has still error: never ending loop after last redirect (I think at line: 1462).
Loop ends after 6 mins.
After entering url, css not loaded.

Maybe to add to _config.php file can help with css:
............
i18n::set_locale('sk_SK');
Config::inst()->update('Director','alternate_base_url','/'); 
...........

Windows 64 bit, Apache/2.4.4 (Win32) OpenSSL/0.9.8y PHP/5.4.23

![ss318](https://cloud.githubusercontent.com/assets/722942/5083758/010e9a14-6efc-11e4-877a-698d23d90f15.jpg)

![ss318a](https://cloud.githubusercontent.com/assets/722942/5083761/09681546-6efc-11e4-9536-a716c14b78cb.jpg)

![ss318b](https://cloud.githubusercontent.com/assets/722942/5083762/12a1ce90-6efc-11e4-92bd-50c1f24107d1.jpg)

**Comment by vinnieupadhyay** [comment]
a&nbsp;p

**Comment by lukereative** [comment]
Closing this as SS3 is now in security only support and will not be fixed for 3.x. If this is still an issue that is affecting you in 4.x then please reopen with new details.
