### ISSUE TITLE
composer/installers change breaks composer create-project and update

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-installer#89]
The change at [composer/installers@316656d40baba4d46ff60f9fc64c52e5ce6b4849](https://github.com/composer/installers/commit/316656d40baba4d46ff60f9fc64c52e5ce6b4849) breaks composer create-project and composer update in existing projects. This is the error that is thrown:

	[ErrorException]
	Argument 1 passed to Composer\Installer\LibraryInstaller::__construct() must implement interface Composer\IO\IOInterface, n  
	one given, called in phar:///Users/fred/bin/composer/src/Composer/Plugin/PluginManager.php on line 250 and defined

A temporary workaround is to edit composer.json to require version 1.0.21 of composer/installers or to invoke composer with the "--no-plugins" option. I'm not sure which is worse.

**Comment by chillu** [comment]
Looks like the commit has been reverted already: https://github.com/composer/installers/issues/232. Could you run an `install` and `update` with a new installer and check if it fixes your issue?

**Comment by oddnoc** [comment]
Yes, the issue is fixed now. I wonder if SilverStripe should specify a more conservative version of composer/installers than "*".

**Comment by tractorcow** [comment]
A happy ending indeed! Thanks for reporting this issue.
