### ISSUE TITLE
Composer issues with 3.2 / self.version

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-installer#90]
At the moment running composer create-project on 3.2.x creates a repo with a detached head (but at the right commit). This doesn't break the initial install (which evaluates self.version as 3.2.x-dev) but further operations cannot determine the correct version.

This seems to have been traced to an issue in composer setting up an incorrect root branch.

**Comment by tractorcow** [comment]
Workaround for the time being is use "3.x-dev" instead of "3.2.x-dev"

**Comment by chillu** [comment]
Do you have a reference to the composer bug? Doesn't look like we've referenced `3.2.x-dev` anywhere in the docs at least (http://doc.silverstripe.org/en/getting_started/composer/)

**Comment by tractorcow** [comment]
Sorry, this issue is the only reference at this point. I need to spend some time to dig into composer itself to locate the source of the issue (and/or verify that indeed it is an issue).

3.2.x-dev is possibly referenced in various composer.json. At least "~3.2" is, although technically 3.x-dev evaluates to 3.9999999 (and meets the various dependencies), it would be nicer if the .2 was respected natively.

At the moment it's really just a quality of life issue, since the workaround is fine for the time being.

**Comment by micschk** [comment]
Found it: https://github.com/silverstripe/silverstripe-framework/pull/3837#issuecomment-72051891
and: https://github.com/micmania1/silverstripe-lumberjack/issues/13

**Comment by chillu** [comment]
THis has long been fixed
