### ISSUE TITLE
3.2 Beta1 Installation Page Web Links targets 

### ISSUE THREAD

**Issue by rogyw** [silverstripe/silverstripe-installer#95]
install.php from downloaded Silverstripe 3.2 Beta1 tar.gz

Several information web links do not open in new _blank browser resulting in user moving away from installer and losing values entered in form. (Some links do open in _blank, so behaviour is inconsistent). 

Examples:
1. Warning message - "Server requirements" _"There are some issues that we recommend you look at before installing, however, you are still able to install the software. Please see below for details. If you are having problems meeting the requirements, see the **server requirements**."_ 
2. Theme section links:
1. Theme "download another"  _"You can change the theme or **download** another from the SilverStripe website after installation"_
2. "Simple " and "tutorial" links  _"**Simple** - our default theme ready to use, or begin the **tutorial**."_
1. http://docs.silverstripe.org/suggested-web-hosts is a broken link in the first paragraph _"Thanks for choosing to use SilverStripe! Please follow the instructions below and you should be up in running in no time.If you get stuck, head over to the installation forum, or check out our list of **suggested web hosts** known to work with SilverStripe."_ 
2. (FYI) Links are pointing to 3.1 Docs not 3.2 docs. http://doc.silverstripe.org/framework/en/tutorials links to http://docs.silverstripe.org/en/3.1/tutorials/ which reports "These tutorials are deprecated, and have been replaced by the new Lessons section."

**Comment by bergice** [comment]
This is referring to the deprecated installation wizard in SS3 which is now in limited support.
